//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.269
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Com.BaseLibrary.Payment.Jh99BillsOrderQuery {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.99bill.com/gatewayapi/services/gatewayOrderQuery", ConfigurationName="Jh99BillsOrderQuery.GatewayOrderQuery")]
    public interface GatewayOrderQuery {
        
        // CODEGEN: 消息 gatewayOrderQueryRequest 的包装命名空间(http://api.seashell.bill99.com)以后生成的消息协定与默认值(http://www.99bill.com/gatewayapi/services/gatewayOrderQuery)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(GatewayOrderDetail))]
        Com.BaseLibrary.Payment.Jh99BillsOrderQuery.gatewayOrderQueryResponse1 gatewayOrderQuery(Com.BaseLibrary.Payment.Jh99BillsOrderQuery.gatewayOrderQueryRequest1 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://gatewayquery.dto.domain.seashell.bill99.com")]
    public partial class GatewayOrderQueryRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string endTimeField;
        
        private string inputCharsetField;
        
        private string merchantAcctIdField;
        
        private string orderIdField;
        
        private int queryModeField;
        
        private int queryTypeField;
        
        private string requestPageField;
        
        private string signMsgField;
        
        private int signTypeField;
        
        private string startTimeField;
        
        private string versionField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string endTime {
            get {
                return this.endTimeField;
            }
            set {
                this.endTimeField = value;
                this.RaisePropertyChanged("endTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string inputCharset {
            get {
                return this.inputCharsetField;
            }
            set {
                this.inputCharsetField = value;
                this.RaisePropertyChanged("inputCharset");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string merchantAcctId {
            get {
                return this.merchantAcctIdField;
            }
            set {
                this.merchantAcctIdField = value;
                this.RaisePropertyChanged("merchantAcctId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string orderId {
            get {
                return this.orderIdField;
            }
            set {
                this.orderIdField = value;
                this.RaisePropertyChanged("orderId");
            }
        }
        
        /// <remarks/>
        public int queryMode {
            get {
                return this.queryModeField;
            }
            set {
                this.queryModeField = value;
                this.RaisePropertyChanged("queryMode");
            }
        }
        
        /// <remarks/>
        public int queryType {
            get {
                return this.queryTypeField;
            }
            set {
                this.queryTypeField = value;
                this.RaisePropertyChanged("queryType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string requestPage {
            get {
                return this.requestPageField;
            }
            set {
                this.requestPageField = value;
                this.RaisePropertyChanged("requestPage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string signMsg {
            get {
                return this.signMsgField;
            }
            set {
                this.signMsgField = value;
                this.RaisePropertyChanged("signMsg");
            }
        }
        
        /// <remarks/>
        public int signType {
            get {
                return this.signTypeField;
            }
            set {
                this.signTypeField = value;
                this.RaisePropertyChanged("signType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string startTime {
            get {
                return this.startTimeField;
            }
            set {
                this.startTimeField = value;
                this.RaisePropertyChanged("startTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
                this.RaisePropertyChanged("version");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://gatewayquery.dto.domain.seashell.bill99.com")]
    public partial class GatewayOrderDetail : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string dealIdField;
        
        private string dealTimeField;
        
        private long feeField;
        
        private long orderAmountField;
        
        private string orderIdField;
        
        private string orderTimeField;
        
        private long payAmountField;
        
        private string payResultField;
        
        private string payTypeField;
        
        private string signInfoField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string dealId {
            get {
                return this.dealIdField;
            }
            set {
                this.dealIdField = value;
                this.RaisePropertyChanged("dealId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string dealTime {
            get {
                return this.dealTimeField;
            }
            set {
                this.dealTimeField = value;
                this.RaisePropertyChanged("dealTime");
            }
        }
        
        /// <remarks/>
        public long fee {
            get {
                return this.feeField;
            }
            set {
                this.feeField = value;
                this.RaisePropertyChanged("fee");
            }
        }
        
        /// <remarks/>
        public long orderAmount {
            get {
                return this.orderAmountField;
            }
            set {
                this.orderAmountField = value;
                this.RaisePropertyChanged("orderAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string orderId {
            get {
                return this.orderIdField;
            }
            set {
                this.orderIdField = value;
                this.RaisePropertyChanged("orderId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string orderTime {
            get {
                return this.orderTimeField;
            }
            set {
                this.orderTimeField = value;
                this.RaisePropertyChanged("orderTime");
            }
        }
        
        /// <remarks/>
        public long payAmount {
            get {
                return this.payAmountField;
            }
            set {
                this.payAmountField = value;
                this.RaisePropertyChanged("payAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string payResult {
            get {
                return this.payResultField;
            }
            set {
                this.payResultField = value;
                this.RaisePropertyChanged("payResult");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string payType {
            get {
                return this.payTypeField;
            }
            set {
                this.payTypeField = value;
                this.RaisePropertyChanged("payType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string signInfo {
            get {
                return this.signInfoField;
            }
            set {
                this.signInfoField = value;
                this.RaisePropertyChanged("signInfo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://gatewayquery.dto.domain.seashell.bill99.com")]
    public partial class GatewayOrderQueryResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string currentPageField;
        
        private string errCodeField;
        
        private string merchantAcctIdField;
        
        private GatewayOrderDetail[] ordersField;
        
        private string pageCountField;
        
        private string pageSizeField;
        
        private string recordCountField;
        
        private string signMsgField;
        
        private int signTypeField;
        
        private string versionField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string currentPage {
            get {
                return this.currentPageField;
            }
            set {
                this.currentPageField = value;
                this.RaisePropertyChanged("currentPage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string errCode {
            get {
                return this.errCodeField;
            }
            set {
                this.errCodeField = value;
                this.RaisePropertyChanged("errCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string merchantAcctId {
            get {
                return this.merchantAcctIdField;
            }
            set {
                this.merchantAcctIdField = value;
                this.RaisePropertyChanged("merchantAcctId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public GatewayOrderDetail[] orders {
            get {
                return this.ordersField;
            }
            set {
                this.ordersField = value;
                this.RaisePropertyChanged("orders");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string pageCount {
            get {
                return this.pageCountField;
            }
            set {
                this.pageCountField = value;
                this.RaisePropertyChanged("pageCount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string pageSize {
            get {
                return this.pageSizeField;
            }
            set {
                this.pageSizeField = value;
                this.RaisePropertyChanged("pageSize");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string recordCount {
            get {
                return this.recordCountField;
            }
            set {
                this.recordCountField = value;
                this.RaisePropertyChanged("recordCount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string signMsg {
            get {
                return this.signMsgField;
            }
            set {
                this.signMsgField = value;
                this.RaisePropertyChanged("signMsg");
            }
        }
        
        /// <remarks/>
        public int signType {
            get {
                return this.signTypeField;
            }
            set {
                this.signTypeField = value;
                this.RaisePropertyChanged("signType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
                this.RaisePropertyChanged("version");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="gatewayOrderQuery", WrapperNamespace="http://api.seashell.bill99.com", IsWrapped=true)]
    public partial class gatewayOrderQueryRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public Com.BaseLibrary.Payment.Jh99BillsOrderQuery.GatewayOrderQueryRequest request;
        
        public gatewayOrderQueryRequest1() {
        }
        
        public gatewayOrderQueryRequest1(Com.BaseLibrary.Payment.Jh99BillsOrderQuery.GatewayOrderQueryRequest request) {
            this.request = request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="gatewayOrderQueryResponse", WrapperNamespace="http://www.99bill.com/gatewayapi/services/gatewayOrderQuery", IsWrapped=true)]
    public partial class gatewayOrderQueryResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public Com.BaseLibrary.Payment.Jh99BillsOrderQuery.GatewayOrderQueryResponse gatewayOrderQueryReturn;
        
        public gatewayOrderQueryResponse1() {
        }
        
        public gatewayOrderQueryResponse1(Com.BaseLibrary.Payment.Jh99BillsOrderQuery.GatewayOrderQueryResponse gatewayOrderQueryReturn) {
            this.gatewayOrderQueryReturn = gatewayOrderQueryReturn;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface GatewayOrderQueryChannel : Com.BaseLibrary.Payment.Jh99BillsOrderQuery.GatewayOrderQuery, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GatewayOrderQueryClient : System.ServiceModel.ClientBase<Com.BaseLibrary.Payment.Jh99BillsOrderQuery.GatewayOrderQuery>, Com.BaseLibrary.Payment.Jh99BillsOrderQuery.GatewayOrderQuery {
        
        public GatewayOrderQueryClient() {
        }
        
        public GatewayOrderQueryClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GatewayOrderQueryClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GatewayOrderQueryClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GatewayOrderQueryClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Com.BaseLibrary.Payment.Jh99BillsOrderQuery.gatewayOrderQueryResponse1 Com.BaseLibrary.Payment.Jh99BillsOrderQuery.GatewayOrderQuery.gatewayOrderQuery(Com.BaseLibrary.Payment.Jh99BillsOrderQuery.gatewayOrderQueryRequest1 request) {
            return base.Channel.gatewayOrderQuery(request);
        }
        
        public Com.BaseLibrary.Payment.Jh99BillsOrderQuery.GatewayOrderQueryResponse gatewayOrderQuery(Com.BaseLibrary.Payment.Jh99BillsOrderQuery.GatewayOrderQueryRequest request) {
            Com.BaseLibrary.Payment.Jh99BillsOrderQuery.gatewayOrderQueryRequest1 inValue = new Com.BaseLibrary.Payment.Jh99BillsOrderQuery.gatewayOrderQueryRequest1();
            inValue.request = request;
            Com.BaseLibrary.Payment.Jh99BillsOrderQuery.gatewayOrderQueryResponse1 retVal = ((Com.BaseLibrary.Payment.Jh99BillsOrderQuery.GatewayOrderQuery)(this)).gatewayOrderQuery(inValue);
            return retVal.gatewayOrderQueryReturn;
        }
    }
}
