//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18033
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Com.BaseLibrary.Payment.Jh99BillsRefundQuery {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.99bill.com/gatewayapi/services/gatewayRefundQuery", ConfigurationName="Jh99BillsRefundQuery.GatewayRefundQuery")]
    public interface GatewayRefundQuery {
        
        // CODEGEN: 消息 queryRequest 的包装命名空间(http://api.seashell.bill99.com)以后生成的消息协定与默认值(http://www.99bill.com/gatewayapi/services/gatewayRefundQuery)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(GatewayRefundQueryResultDto))]
        Com.BaseLibrary.Payment.Jh99BillsRefundQuery.queryResponse query(Com.BaseLibrary.Payment.Jh99BillsRefundQuery.queryRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18033")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://gatewayrefundquery.dto.domain.seashell.bill99.com")]
    public partial class GatewayRefundQueryRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string rOrderIdField;
        
        private string customerBatchIdField;
        
        private string endDateField;
        
        private string lastupdateEndDateField;
        
        private string lastupdateStartDateField;
        
        private string merchantAcctIdField;
        
        private string orderIdField;
        
        private string requestPageField;
        
        private string seqIdField;
        
        private string signMsgField;
        
        private string signTypeField;
        
        private string startDateField;
        
        private string statusField;
        
        private string versionField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string ROrderId {
            get {
                return this.rOrderIdField;
            }
            set {
                this.rOrderIdField = value;
                this.RaisePropertyChanged("ROrderId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string customerBatchId {
            get {
                return this.customerBatchIdField;
            }
            set {
                this.customerBatchIdField = value;
                this.RaisePropertyChanged("customerBatchId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string endDate {
            get {
                return this.endDateField;
            }
            set {
                this.endDateField = value;
                this.RaisePropertyChanged("endDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string lastupdateEndDate {
            get {
                return this.lastupdateEndDateField;
            }
            set {
                this.lastupdateEndDateField = value;
                this.RaisePropertyChanged("lastupdateEndDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string lastupdateStartDate {
            get {
                return this.lastupdateStartDateField;
            }
            set {
                this.lastupdateStartDateField = value;
                this.RaisePropertyChanged("lastupdateStartDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string merchantAcctId {
            get {
                return this.merchantAcctIdField;
            }
            set {
                this.merchantAcctIdField = value;
                this.RaisePropertyChanged("merchantAcctId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string orderId {
            get {
                return this.orderIdField;
            }
            set {
                this.orderIdField = value;
                this.RaisePropertyChanged("orderId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string requestPage {
            get {
                return this.requestPageField;
            }
            set {
                this.requestPageField = value;
                this.RaisePropertyChanged("requestPage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string seqId {
            get {
                return this.seqIdField;
            }
            set {
                this.seqIdField = value;
                this.RaisePropertyChanged("seqId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string signMsg {
            get {
                return this.signMsgField;
            }
            set {
                this.signMsgField = value;
                this.RaisePropertyChanged("signMsg");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string signType {
            get {
                return this.signTypeField;
            }
            set {
                this.signTypeField = value;
                this.RaisePropertyChanged("signType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string startDate {
            get {
                return this.startDateField;
            }
            set {
                this.startDateField = value;
                this.RaisePropertyChanged("startDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
                this.RaisePropertyChanged("version");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18033")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://gatewayrefundquery.dto.domain.seashell.bill99.com")]
    public partial class GatewayRefundQueryResultDto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string rOrderIdField;
        
        private string dealOtherNameField;
        
        private string failReasonField;
        
        private string lastUpdateTimeField;
        
        private string orderAmoutField;
        
        private string orderIdField;
        
        private string orderTimeField;
        
        private string ownerFeeField;
        
        private string payTypeDescField;
        
        private string sequenceIdField;
        
        private string signInfoField;
        
        private string statusField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string ROrderId {
            get {
                return this.rOrderIdField;
            }
            set {
                this.rOrderIdField = value;
                this.RaisePropertyChanged("ROrderId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string dealOtherName {
            get {
                return this.dealOtherNameField;
            }
            set {
                this.dealOtherNameField = value;
                this.RaisePropertyChanged("dealOtherName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string failReason {
            get {
                return this.failReasonField;
            }
            set {
                this.failReasonField = value;
                this.RaisePropertyChanged("failReason");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string lastUpdateTime {
            get {
                return this.lastUpdateTimeField;
            }
            set {
                this.lastUpdateTimeField = value;
                this.RaisePropertyChanged("lastUpdateTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string orderAmout {
            get {
                return this.orderAmoutField;
            }
            set {
                this.orderAmoutField = value;
                this.RaisePropertyChanged("orderAmout");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string orderId {
            get {
                return this.orderIdField;
            }
            set {
                this.orderIdField = value;
                this.RaisePropertyChanged("orderId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string orderTime {
            get {
                return this.orderTimeField;
            }
            set {
                this.orderTimeField = value;
                this.RaisePropertyChanged("orderTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string ownerFee {
            get {
                return this.ownerFeeField;
            }
            set {
                this.ownerFeeField = value;
                this.RaisePropertyChanged("ownerFee");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string payTypeDesc {
            get {
                return this.payTypeDescField;
            }
            set {
                this.payTypeDescField = value;
                this.RaisePropertyChanged("payTypeDesc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string sequenceId {
            get {
                return this.sequenceIdField;
            }
            set {
                this.sequenceIdField = value;
                this.RaisePropertyChanged("sequenceId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string signInfo {
            get {
                return this.signInfoField;
            }
            set {
                this.signInfoField = value;
                this.RaisePropertyChanged("signInfo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18033")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://gatewayrefundquery.dto.domain.seashell.bill99.com")]
    public partial class GatewayRefundQueryResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string currentPageField;
        
        private string errCodeField;
        
        private string merchantAcctIdField;
        
        private int pageCountField;
        
        private int pageSizeField;
        
        private int recordCountField;
        
        private GatewayRefundQueryResultDto[] resultsField;
        
        private string signMsgField;
        
        private string signTypeField;
        
        private string versionField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string currentPage {
            get {
                return this.currentPageField;
            }
            set {
                this.currentPageField = value;
                this.RaisePropertyChanged("currentPage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string errCode {
            get {
                return this.errCodeField;
            }
            set {
                this.errCodeField = value;
                this.RaisePropertyChanged("errCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string merchantAcctId {
            get {
                return this.merchantAcctIdField;
            }
            set {
                this.merchantAcctIdField = value;
                this.RaisePropertyChanged("merchantAcctId");
            }
        }
        
        /// <remarks/>
        public int pageCount {
            get {
                return this.pageCountField;
            }
            set {
                this.pageCountField = value;
                this.RaisePropertyChanged("pageCount");
            }
        }
        
        /// <remarks/>
        public int pageSize {
            get {
                return this.pageSizeField;
            }
            set {
                this.pageSizeField = value;
                this.RaisePropertyChanged("pageSize");
            }
        }
        
        /// <remarks/>
        public int recordCount {
            get {
                return this.recordCountField;
            }
            set {
                this.recordCountField = value;
                this.RaisePropertyChanged("recordCount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public GatewayRefundQueryResultDto[] results {
            get {
                return this.resultsField;
            }
            set {
                this.resultsField = value;
                this.RaisePropertyChanged("results");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string signMsg {
            get {
                return this.signMsgField;
            }
            set {
                this.signMsgField = value;
                this.RaisePropertyChanged("signMsg");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string signType {
            get {
                return this.signTypeField;
            }
            set {
                this.signTypeField = value;
                this.RaisePropertyChanged("signType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
                this.RaisePropertyChanged("version");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="query", WrapperNamespace="http://api.seashell.bill99.com", IsWrapped=true)]
    public partial class queryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public Com.BaseLibrary.Payment.Jh99BillsRefundQuery.GatewayRefundQueryRequest request;
        
        public queryRequest() {
        }
        
        public queryRequest(Com.BaseLibrary.Payment.Jh99BillsRefundQuery.GatewayRefundQueryRequest request) {
            this.request = request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="queryResponse", WrapperNamespace="http://www.99bill.com/gatewayapi/services/gatewayRefundQuery", IsWrapped=true)]
    public partial class queryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public Com.BaseLibrary.Payment.Jh99BillsRefundQuery.GatewayRefundQueryResponse queryReturn;
        
        public queryResponse() {
        }
        
        public queryResponse(Com.BaseLibrary.Payment.Jh99BillsRefundQuery.GatewayRefundQueryResponse queryReturn) {
            this.queryReturn = queryReturn;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface GatewayRefundQueryChannel : Com.BaseLibrary.Payment.Jh99BillsRefundQuery.GatewayRefundQuery, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GatewayRefundQueryClient : System.ServiceModel.ClientBase<Com.BaseLibrary.Payment.Jh99BillsRefundQuery.GatewayRefundQuery>, Com.BaseLibrary.Payment.Jh99BillsRefundQuery.GatewayRefundQuery {
        
        public GatewayRefundQueryClient() {
        }
        
        public GatewayRefundQueryClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GatewayRefundQueryClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GatewayRefundQueryClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GatewayRefundQueryClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Com.BaseLibrary.Payment.Jh99BillsRefundQuery.queryResponse Com.BaseLibrary.Payment.Jh99BillsRefundQuery.GatewayRefundQuery.query(Com.BaseLibrary.Payment.Jh99BillsRefundQuery.queryRequest request) {
            return base.Channel.query(request);
        }
        
        public Com.BaseLibrary.Payment.Jh99BillsRefundQuery.GatewayRefundQueryResponse query(Com.BaseLibrary.Payment.Jh99BillsRefundQuery.GatewayRefundQueryRequest request) {
            Com.BaseLibrary.Payment.Jh99BillsRefundQuery.queryRequest inValue = new Com.BaseLibrary.Payment.Jh99BillsRefundQuery.queryRequest();
            inValue.request = request;
            Com.BaseLibrary.Payment.Jh99BillsRefundQuery.queryResponse retVal = ((Com.BaseLibrary.Payment.Jh99BillsRefundQuery.GatewayRefundQuery)(this)).query(inValue);
            return retVal.queryReturn;
        }
    }
}
